action_create_object(circle_squiggle, 100, 0);
action_create_object(circle_squiggle, 200, 0);
action_create_object(circle_squiggle, 300, 0);
action_create_object(circle_squiggle, 400, 0);
action_create_object(circle_squiggle, 500, 0);
action_create_object(circle_squiggle, 600, 0);
action_create_object(circle_squiggle, 700, 0);
action_create_object(circle_squiggle, 800, 0);
action_create_object(circle_squiggle, 900, 0);
